package com.likeseca.erp.database.exception;

public enum ExceptionCode {
    DB_CONNECTION_FAILED,
    DB_AUTHENTICATION_FAILED,
    DB_TIMEOUT,
    DB_HOST_NOT_FOUND,
    MAX_CONNECTIONS_EXCEEDED,
    SCHEMA_BOOTSTRAP_FAILED,
    TABLE_NOT_FOUND,
    DUPLICATE_KEY,
    FOREIGN_KEY_VIOLATION,
    NULL_CONSTRAINT_VIOLATION,
    TRANSACTION_FAILED,
    UNAUTHORIZED_TABLE_ACCESS,
    UNAUTHORIZED_COLUMN_ACCESS,
    INVALID_CONFIGURATION,
    GENERIC_SQL_FAILURE
}
