db.host=erp-integration-mysql.ch444ikasa7s.ap-south-1.rds.amazonaws.com
db.port=3306
db.name=erp_subsystem
db.username=erp_admin
db.password=DarshanDiddyOOAD
db.pool.maxSize=10
db.backup.dir=backups
db.dump.command=mysqldump
db.restore.command=mysql
